### ISSUE TITLE
Console logs a quite spamy

### ISSUE THREAD

**Issue by Daaaab** [ravipatel147/navigate#2]
I think that logs from your library spams console a little bit to much. They doesn't provide too much value for a user, and its really hard to find my own logs between them. Otherwise great lib!

**Comment by ravipatel147** [comment]
Thanks, @Daaaab. Let I  or @koyachi correct this then inform you here.

**Comment by ravipatel147** [comment]
@koyachi Can you able to do this things

**Comment by ravipatel147** [comment]
@Daaaab  Update with the latest version to avoid console
