### ISSUE TITLE
I love what NAVIGATE  brought but i still dont understand how it work?

### ISSUE THREAD

**Issue by chrisgate** [ravipatel147/navigate#4]
hi @ravipatel147 ,
Nice work!
Please I  still dont understand how it work?
All i see is Navigate to home and home.....Can u update the example with three pages like:
Page 1,Page2 and Page3,
where they naviggate from one place to other and do back too.

Thabks

**Comment by ravipatel147** [comment]
@chrisgate Please update the version. and as per your demand you can, I did create an example for you: https://github.com/ravipatel147/navigate/tree/master/example_with_threepage
