### ISSUE TITLE
Pop delay when using Hero widget. Estimated .5-1sec delay.

### ISSUE THREAD

**Issue by jaasaria** [ravipatel147/navigate#5]
Hi, first thank you for creating this project.

My concern is, after implementing Hero widget. I found out after clicking appbar back button the page give me short delay before closing.

Also tried removing the Hero widget and everything back to normal and smooth closing.

**Comment by ravipatel147** [comment]
@jaasaria Can you please explain with use case  of regenerating issue with code

**Comment by ravipatel147** [comment]
Closed due to no response getting
